### ISSUE TITLE
Set_the_shortcut_key_for_the_plug-in[快捷键]

### ISSUE THREAD

**Issue by jifeng2008** [hegde5/VS-Code-PyDoc-Extension#3]
I'm a beginner in Python,
Typing commands is cumbersome every time you use the plug-in
So I want a shortcut to use it

**Comment by hegde5** [comment]
@jifeng2008 Thank you for opening the issue. Sure, that makes sense. I will look into adding a shortcut soon.

**Comment by hegde5** [comment]
Version `0.4.0` of this extension has the new shortcut to generate the docstring.
