### ISSUE TITLE
Add "return" in the generated docstring

### ISSUE THREAD

**Issue by hegde5** [hegde5/VS-Code-PyDoc-Extension#6]
Currently the docstring generated for functions is of this format:
```
    """ Description
    :type a:
    :param a:

    :type b:
    :param b:

    :raises:

    :rtype:
    """
```

Add `return` to the generated docstring as it gives the user the option to explain what the function is expected to return. Please make sure the `return` is added to only docstrings generated for functions and not classes.

**Comment by neckenth** [comment]
I can take this on. Can I be assigned?

**Comment by hegde5** [comment]
Hello @neckenth! Thanks a lot for showing interest in contributing to this repository. But, @ThiagoDella has already created a PR that would close this issue.
