### ISSUE TITLE
[not relevant]

### ISSUE THREAD

**Issue by weiss-d** [hegde5/VS-Code-PyDoc-Extension#83]
Hello and thanks for this useful extension!

I stumbled upon a problem when I had some tricky regexps needed to be delimited with three quotes.
I used double quotes from habit. And then when I typed """ beneath the function def, nothing happened.
Also when I pressed Ctrl+Alt+B it said:
> Please select a valid function

When I replaced """ with ''' everything worked fine.

**Comment by hegde5** [comment]
Hi @weiss-d! Thanks a lot for your feedback and for opening the issue.

That's interesting. Did you select the function definition before hitting `Ctrl + Alt + B`? 

If yes, then could you please provide the steps to reproduce the issue with a sample function? Doing so would help me understand and reproduce the issue on my side and work on a fix for it.

Thanks for your time!

**Comment by weiss-d** [comment]
@hegde5, I'm terribly sorry, but I posted this issue in a wrong repo. 😓 Please, delete it.
It was intended for  "NilsJPWerner / autoDocstring"
